# Generated by Django 5.0.6 on 2024-06-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_id_comment_uuid_remove_issue_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='contributor',
            new_name='user',
        ),
    ]
